config/routes.rb
Rails.application.routes.draw do
  resources :url_maps ,  except: [:edit,:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/:id', to: 'url_maps#redirect'
  root 'url_maps#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_map.rb
class UrlMap < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_maps_controller.rb
class UrlMapsController < ApplicationController
  before_action :set_url_map, only: [:show, :edit, :update, :destroy]

  # GET /url_maps
  # GET /url_maps.json
  def index
    @url_maps = UrlMap.all
  end

  # GET /url_maps/1
  # GET /url_maps/1.json
  def show
  end

  # GET /url_maps/new
  def new
    @url_map = UrlMap.new
  end

  # GET /url_maps/1/edit
  def edit
  end

  # POST /url_maps
  # POST /url_maps.json
  def create
    @url_map = UrlMap.new(url_map_params)

    respond_to do |format|
      if @url_map.save
        format.html { redirect_to @url_map, notice: "#{request.base_url}/#{@url_map.id}" }
        format.json { render :show, status: :created, location: @url_map }
      else
        format.html { render :new }
        format.json { render json: @url_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /url_maps/1
  # PATCH/PUT /url_maps/1.json
  def update
    respond_to do |format|
      if @url_map.update(url_map_params)
        format.html { redirect_to @url_map, notice: 'Url map was successfully updated.' }
        format.json { render :show, status: :ok, location: @url_map }
      else
        format.html { render :edit }
        format.json { render json: @url_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /url_maps/1
  # DELETE /url_maps/1.json
  def destroy
    @url_map.destroy
    respond_to do |format|
      format.html { redirect_to url_maps_url, notice: 'Url map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def redirect
    redirect_to UrlMap.find(params[:id]).to
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url_map
      @url_map = UrlMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_map_params
      params.fetch(:url_map, {}).permit(:to)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_maps_helper.rb
module UrlMapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_maps/_form.html.erb
<%= form_with(model: url_map, local: true) do |form| %>
  <%= form.text_field :to %>
  <% if url_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url_map.errors.count, "error") %> prohibited this url_map from being saved:</h2>

      <ul>
      <% url_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/url_maps/edit.html.erb
<h1>Editing Url Map</h1>

<%= render 'form', url_map: @url_map %>

<%= link_to 'Show', @url_map %> |
<%= link_to 'Back', url_maps_path %>

app/views/url_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Url Maps</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  </tbody>
</table>

<br>

<%= link_to 'New Url Map', new_url_map_path %>

app/views/url_maps/new.html.erb
<h1>New Url Map</h1>

<%= render 'form', url_map: @url_map %>

<%= link_to 'Back', url_maps_path %>

app/views/url_maps/show.html.erb
<p id="notice"><%= notice %></p>

<!--<%#= link_to 'Edit', edit_url_map_path(@url_map) %> |-->
<%= link_to 'Back', url_maps_path %>